application: chugliaunty
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
  
- url: .*
  script: chugliaunty.app

inbound_services:
- mail

libraries:
- name: webapp2
  version: "2.5.2"
